### PR TITLE
Update UnionMangas with their new URL

### PR DESCRIPTION
**Pull request by masgritz**
They changed their domain a couple of days ago and it broke the extension.

### CODE REVIEW

**Comment by arkon** [comment]
Remove the Gradle change from this PR.

**Comment by Lelou123** [comment]
Hello, I am too waiting the changing about the extension...
Since now I am grateful for the work, Thanks :D

**Comment by masgritz** [comment]
Apologies, Android Studio asked me to update it and I didn't think of that at that moment. I have reverted the gradle change to the original version.

**Comment by masgritz** [comment]
I decided to rebase it back to before the gradle change in order to avoid polluting the commits list in this repository. Everything should be fine now, let me know if any changes are necessary.

**Comment by Lelou123** [comment]
When will give to access the extension?

**Pull request merged**
