### PR TITLE
Fix "Page list empty" for KissManga

### PR DESCRIPTION
**Pull request by i404788**

### CODE REVIEW

**Comment by arkon** [comment]
Update the version code in build.gradle

**Comment by arkon** [comment]
Idk if this actually fixed it or not, but you'll still get errors if your IP is banned.

**Comment by armangido** [comment]
> Idk if this actually fixed it or not, but you'll still get errors if your IP is banned.

they've unbanned ppls now, idk what is there reason

**Comment by i404788** [comment]
As far as I've seen from the kissmanga source this is the only thing that needed to change for it to work.

**Comment by i404788** [comment]
They just seem to have changed it again, it might randomize the suffix on a timer...

**Pull request merged**
