### PR TITLE
TMO Update

### LINKED ISSUE #2011: [Bug] TuMangaOnline : Not loading any manga, stuck in retry
### Device information
* Tachiyomi extension version: 1.2.15
* Tachiyomi version: 8.4.5
* Android version: 10

## Steps to reproduce
1. download the extension tuMangaOnline version 1.2.15
2. try to open any manga using this source

### Expected behavior
That there will be the manga that you want to read without problems

### Actual behavior
when the sleeve is opened it stays on a black screen with a button in the center that says "retry"

### Other details
I'm getting a oneplus 6t cell phone, today the application from version 1.2.14 to version 1.2.15 was updated but it still doesn't work

### PR DESCRIPTION
**Pull request by happywillow0**
Fixes #2011 
They removed lazy loading again but kept a bunch of anti-scraping images which are filtered out.

### CODE REVIEW

**Comment by happywillow0** [comment]
Tested 01/07, looking fine. Let me know when you want to pull and I can triple check before marking ready.

**Comment by arkon** [comment]
Can you check now?

**Comment by MerradOklom** [comment]
I follow other repositories that use this source and one of them had to fix it 1 hour ago.

**Comment by happywillow0** [comment]
Updated and tested 1/8

**Pull request merged**
