### PR TITLE
mmrcms: update on-manga url

### PR DESCRIPTION
**Pull request by yshalsager**
* site is moving to new url

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Has it moved already?

**Comment by yshalsager** [comment]
@CarlosEsco they are requesting the users to use the new address in a homepage pop-up and banner.
image

**Comment by CarlosEsco** [comment]
Ok can you update the build.gradle version for mmrcms so I can merge

**Comment by yshalsager** [comment]
@CarlosEsco Done

**Pull request merged**
