### PR TITLE
[New] MangaMx

### LINKED ISSUE #1670: [Source Request] [Spanish]
MangaMx
URL:

[MangaMx](https://manga-mx.com/)

### PR DESCRIPTION
**Pull request by happywillow0**
Closes #1670

I really need to stop coding and get proper sleep.
But I found out how to post on mangamx to get the chapter list so I had to finish the extension.

~~Icons needed~~ thank you.

### CODE REVIEW

**Comment by MerradOklom** [comment]
Thank you very much for all your time and effort. I hope you rest well.

**Comment by happywillow0** [comment]
To do

Forgot to update searchMangaFromElement

**Comment by as280093** [comment]
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3757720/ic_launcher.zip)

**Comment by happywillow0** [comment]
Done and tested. Everything should be good.

**Pull request merged**
