### PR TITLE
MangaHere fix

### PR DESCRIPTION
**Pull request by SYtor**
title

### CODE REVIEW

**Comment by CarlosEsco** [comment]
why did you change the id number?

**Comment by CarlosEsco** [comment]
also you need to upgrade the build.gradle file version.  then let me know when you finish as it seems you are still adding commits

**Comment by SYtor** [comment]
Website had completely changed and comment for `versionId `says that it should be changed too. Should I still use previous value?

**Comment by CarlosEsco** [comment]
build.gradle version needs incremented.

this id is not an id that should change.

**Comment by SYtor** [comment]
Oh yes, I've missed it

**Comment by SYtor** [comment]
You can merge, I've finished making changes

**Comment by arkon** [comment]
Would these changes work for Mangago too?

**Comment by SYtor** [comment]
MangaFox (fanfox) uses same algorithm as here , but Mangago use some unreadable obfuscation, I don't think algorithms are alike. Also, is it possible to bypass Cloudflare DDoS protection?

**Comment by shogrran** [comment]
Sorry, I tried searching and found this site. Is mangahere on tachiyomi not working anymore? Am I the only one with downloads not working right now? (newbie here). using mangahere extension 1.2.15

**Comment by scb261** [comment]
@shogrran it works for me, try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis). For more questions refer to [the Discrord server](https://discord.gg/tachiyomi)

**Pull request merged**
