### PR TITLE
FMReader - new factory extension

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Work in progress, making a factory extension based off of the LHTranslation extension.  Still need to make a few more adjustments.  

Source list:
    LHTranslation(), - deprecates an older extension
    MangaHato(), - closes https://github.com/inorichi/tachiyomi-extensions/issues/1559
    ManhwaScan(),
    MangaTiki(),
    MangaBone(), - closes https://github.com/inorichi/tachiyomi-extensions/issues/1536
    YoloManga(),
    MangaLeer(),
    AiLoveManga(),
    ReadComicOnlineOrg(),
    MangaWeek(),
    HanaScan(), - deprecates an older extension (RawQQ)
    RawLH(), - deprecates an older extension
    ManhwaEighteen(),  - deprecates an older extension
    TruyenTranhLH(), - deprecates an older extension
    EighteenLHPlus(),
    MangaTR(), - closes https://github.com/inorichi/tachiyomi-extensions/issues/828
    Comicastle() - closes https://github.com/inorichi/tachiyomi-extensions/issues/1345

Icons are from the LHTranslation extension, I'm open to reusing them or changing them.

### CODE REVIEW

**Comment by MerradOklom** [comment]
Hi. If you don't mind, I found two other sources that use this "LHReader":

Spanish: https://yolomanga.ca/
Spanish: https://mangaleer.com/

I'll edit this comment if I find another one.

**Comment by SnakeDoc83** [comment]
Where I'm currently at with sources:

        LHTranslation(), - deprecates an older extension
        MangaHato(),
        ManhwaScan(),
        MangaTiki(),
        MangaBone(),
        YoloManga(),
        MangaLeer(),
        AiLoveManga(),
        ReadComicOnline(), - deprecates an older extension
        MangaWeek(),
        HanaScan(), - deprecates an older extension (RawQQ)
        RawLH(), - deprecates an older extension
        ManhwaEighteen(),  - deprecates an older extension
        TruyenTranhLH(), - deprecates an older extension
        EighteenLHPlus(),
        MangaTR()

That list includes what I mentioned in my original post, as well as what @MerradOklom posted.  Still going to be working on this for a while, feel free to post more sources while this is open.

**Comment by MerradOklom** [comment]
I couldn't find more sources, but I noticed some of them use this "lazy load":
https://mangatiki.com/app/manga/themes/default/assets/images/lazy-load.gif
Maybe that's the reader's real icon.

**Comment by MerradOklom** [comment]
After investigating a bit I discovered that this sites are build with Flat Manga CMS by Huy Khong:
https://codecanyon.net/item/flat-manga-build-your-own-manga-reader-site/5611894
FlatManga

**Comment by as280093** [comment]
After checking the github repo sent by @MerradOklom i found this icon
favicon
And here it the favicon
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3661023/ic_launcher.zip)

**Comment by arkon** [comment]
Is this still a WIP?

**Comment by SnakeDoc83** [comment]
Yeah, it's mostly done except for a couple small things I wanted to
perfect.  Kind of stepped away from it for a bit so that I could look at it
with fresh eyes.  I'll finish up today or tomorrow and let you know.

**Comment by SnakeDoc83** [comment]
@arkon This is ready to be looked at.

**Pull request merged**
