### PR TITLE
Remove MyAnimeList Free Manga (1/2)

### LINKED ISSUE #3466: My Anime List free manga
# Source information
* Source name: My Anime List Free Manga
* Source extension version: 1.2.1

## Steps to reproduce
1. Browse Manga

## Issue/Request
It seems mal free manga has quietly dissapeared, as such this extension no longer works and should be removed

## Other details
Wasn't sure what to put this under so I just put it in a blank file.

### PR DESCRIPTION
**Pull request by alessandrojean**
Since the service doesn't exist anymore, the extension can be removed.

Closes #3466.

### CODE REVIEW

**Comment by TacoTheDank** [comment]
@alessandrojean @arkon Was this correct? Checking now, the site seems to work perfectly fine for me. They seemed to be experiencing 403 errors though for other people, and they were fixing it, I guess. Also VPNs may no longer be working for accessing the site.

https://mobile.twitter.com/myanimelist/status/1271027418137071616
https://www.reddit.com/r/MyAnimeList/comments/h7tq7o/can_anyone_access_myanimelist_right_now_i_still/
https://www.reddit.com/r/MyAnimeList/

**Comment by alessandrojean** [comment]
@TacoTheDank If you open the site at the page that previously have the mangas to read (https://myanimelist.net/read/manga), you will see that now it's 404, at least for me and for the user that opened the issue.

Apparently, people in the MAL's forum are also saying the same, that the service (MAL Free Manga) doesn't exist anymore.

**Comment by arkon** [comment]
When the issue was created in only saw paid content.

**Comment by TacoTheDank** [comment]
@alessandrojean Mmm, I see. That's a shame :(

**Pull request merged**
