### PR TITLE
Added English Source: LHTranslation

### LINKED ISSUE #1014: [Source Request] [English] LHTranslations.net
https://lhtranslation.net/index.html

### PR DESCRIPTION
**Pull request by DitFranXX**
Close #1014 

This site is really similar to rawLH. most of codes are CCCV-ed from rawLH

### CODE REVIEW

**Comment by as280093** [comment]
copy res folder of RawLH to this for icons

**Comment by DitFranXX** [comment]
Didn't notice that it uses same icon.

**Comment by as280093** [comment]
there are 2 extension with same icons 
one rawLH & TruyenTranhLH

**Comment by as280093** [comment]
all are based on their website or their site favicon

**Pull request merged**
