### PR TITLE
Add new source mangahasu

### PR DESCRIPTION
**Pull request by Pavkazzz**
Add new source

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Remove the id

**Comment by Pavkazzz** [comment]
Done

**Comment by CarlosEsco** [comment]
? There was no new commit

**Comment by Pavkazzz** [comment]
https://github.com/inorichi/tachiyomi-extensions/pull/505/commits/fd7542cee4eeb2474eb2501bf2b391040155fa77 
This one fix this

**Comment by CarlosEsco** [comment]
Not it didn't that fixed package only

**Comment by Pavkazzz** [comment]
Sorry, my bad. Done

**Pull request merged**
