### PR TITLE
Some fixes for Manga Plus

### PR DESCRIPTION
**Pull request by alessandrojean**
- Potentially fix thumbnail images not showing (#1143);
- Remove duplicate content, only showing the english titles (#866);
- Fix the "Open in browser" with a workaround based on the MangaRock one;
- Show the error message from the API when it occurs.

I pretend to implement the Spanish version (#845), but I am not sure what the steps to do that. Is it okay to create a new extension in the `all` folder that includes the both and create an update to the existing one where all the methods throws an Exception telling the user to install the new Extension and migrate the existing titles in their library? If this is okay, I pretend to do that with Manga Plus; and in a similar case unite the MangasProject and MangaLivre with another english source (7Sama) that is from the same site in a new extension in a future PR. If this steps are not okay, what are the correct ones?

### CODE REVIEW

**Comment by MerradOklom** [comment]
Hi, does this pr also fix the Open in Browser? It goes to the api page instead of the selected manga info.

**Comment by alessandrojean** [comment]
@MerradOklom Actually no, but I can study how to change that and submit a new PR later if I succeed.

**Comment by alessandrojean** [comment]
Based on the MangaRock solution, I have made the `mangaDetailsRequest` always return the site url instead of the API one. As the manga `url` is set as `#/titles/{id}` since the first version of the extension, I believe this should not make the app stop handling the mangas in the library, because the `url` was not changed. I tested with some titles in my library before changing this and they are working fine. So, I believe the "Open in browser" feature is fixed too, @MerradOklom.

**Comment by MerradOklom** [comment]
Thank you for all your time and effort.

**Comment by arkon** [comment]
> I pretend to implement the Spanish version (#845), but I am not sure what the steps to do that. Is it okay to create a new extension in the all folder that includes the both and create an update to the existing one where all the methods throws an Exception telling the user to install the new Extension and migrate the existing titles in their library?

That could work. I believe Webtoons was recently updated to support other languages too, so you could look at that as well. That can be in another PR though.

**Comment by MercerBoi** [comment]
@alessandrojean, hey, thanks for the work, but unfortunately the thumbnail issue doesn't seem to be resolved (for me, at least). I discovered that I have to select each of the manga individually to load their covers, and only then it appears on the catalogue, but even that has exceptions, as you can see from the screenshot given below.

Screenshot_2019-05-30-10-42-35-187_eu kanade tachiyomi

**Comment by alessandrojean** [comment]
@MercerBoi This happens because the app registered in the database the old thumbnail url, even for the mangas you don't have in your library. So, to fix that, you can go to Preferences > Advanced and do the "Clear Database" and "Refresh library metadata". I have done this here and all the thumbnails came back.

Unfortunately I realized now that in the Popular Mangas I forgot to do the trick to make the thumbnails stay forever, so eventually this can happen again with the titles that are not in your library. But don't worry, I will fix that soon.

**Comment by MercerBoi** [comment]
Thank you, it works! Keep up the good work, man. It's much appreciated.

**Pull request merged**
