### PR TITLE
Mangaonlinebiz latest support. Normalize genres name

### PR DESCRIPTION
**Pull request by Pavkazzz**

### CODE REVIEW

**Comment by as280093** [comment]
if possible change the icons too
sample
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3317588/ic_launcher.5.zip)

**Comment by Pavkazzz** [comment]
> if possible change the icons too
> sample
> [ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3317588/ic_launcher.5.zip)

It's amazing, thank you!

**Comment by as280093** [comment]
i think you missed 512 web img

**Comment by as280093** [comment]
sorry but looks like you kept web hi res icon in wrong folder
Screenshot_2019-06-23-15-11-25-605_com android chrome

It should just inside the res folder as shown below
Screenshot_2019-06-23-15-10-27-714_com android chrome

**Comment by Pavkazzz** [comment]
@as280093 Thx again

**Comment by arkon** [comment]
The other icons are in the wrong folder.

**Comment by as280093** [comment]
lol ya multiple 📂 folders mixed

**Comment by Pavkazzz** [comment]
@arkon Thx, fixed

**Comment by Pavkazzz** [comment]
@arkon Merge pls.

**Pull request merged**
