### PR TITLE
add pufei comic

### PR DESCRIPTION
**Pull request by feilongfl**
add pufei comic(zh-cn)
http://pufei.net

This plugin will be garbled in the current version due to webpage coding issues. 
Patch https://github.com/inorichi/tachiyomi/pull/2031 fix this problem.

### CODE REVIEW

**Comment by as280093** [comment]
change the logo to this 

ic_launcher

RES file zip
[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/3173829/res.zip)

**Comment by feilongfl** [comment]
I have changed icon to your zip file.

@as280093

**Comment by arkon** [comment]
You could temporarily replicate the behaviour of `asJsoup` (with the different encoding) within the extension for better backwards compatibility. I don't think the main app will be updated with that (if merged) for a while since stable releases are relatively sparse.

**Comment by feilongfl** [comment]
@arkon 
All right, I have add custom jsoup in my ext.

**Pull request merged**
