### PR TITLE
Add support for My Manga Reader CMS sources (many, many sources)

### LINKED ISSUE #34: [English] http://www.readcomics.website/
http://www.readcomics.website/

Can you please readcomics.website as a catalogue?

### LINKED ISSUE #57: readcomics.tv dead
I'm not getting any links loading from it and can't access it from my browser, either. It's gone

### LINKED ISSUE #98: [English] readcomics.website
(CATALOGUE) SOURCE REQUESTS:
  One source per issue, create more issues if you have more websites
  Check for duplicates, use search (in issues, not the global one)
  Put the name of the site as Title, replace this text with clickable link to the site
BUGS:
  Provide tachiyomi version as well as version of source the report is about

### LINKED ISSUE #101: [Site Request] iranian manga reader
I work in an iranian  manga group  and we tranlate comic/manga for free.the problem is that  because of Religious reasons goverment suspend us/: we change domain every time but lost many of our readers. is there a way that we can publish our translates on Tachiyomi ?
there are some changes that need to be done,like language.
this is a sample site for test:
http://trinityreader.tk/

we will be very grateful if someone can do it for us, It's about three years of effort.

### PR DESCRIPTION
**Pull request by null-dev**
Sources added by this extension:
- AR: مانجا اون لاين
- AR: Manga FYI
- EN: Read Comics Online
- EN: Fallen Angels Scans
- EN: Mangawww Reader
- EN: MangaForLife
- EN: Manga Spoil
- EN: DManga
- EN: Chibi Manga Reader
- EN: ZXComic
- EN: Mangacox
- EN: KoManga
- EN: Manganimecan
- EN: Hentai2Manga
- EN: White Cloud Pavilion
- EN: 4 Manga
- EN: XYXX.INFO
- ES: My-mangas.com
- ES: SOS Scanlation
- FR: Manga-LEL
- FR: Manga Etonnia
- FR: Scan FR
- FR: ScanFR.com
- FR: Manga FYI
- FR: Mugiwara
- FR: scans-manga
- ID: Manga Desu
- ID: MangaOnline
- ID: Komikid
- ID: MangaID
- ID: Manga Seru
- ID: Manga FYI
- JA: Mangazuki RAWS
- JA: MangaRAW
- PL: Candy Scans
- PL: ToraScans
- PT: Comic Space
- PT: Mangás Yuri
- RU: NAKAMA
- TR: MangAoi
- TR: MangaHanta
- TR: ManhuaTR
- VI: Fallen Angels Scans
- OTHER: HentaiShark

I found out that a bunch of popular websites use the same CMS software!

Instead of writing a source for every manga website that uses [My Manga Reader CMS](https://getcyberworks.com/product/manga-reader-cms/), I decided to write a generator that would generate them for me! I've enabled generation for the sources above, there may still be more sources that support generation.

*If you find a source that uses My Manga Reader CMS (there are many here: <https://www.google.ca/search?q="Powered+by+my+Manga+Reader+CMS">), please help me out by posting the generation code for it!* It's easy:

1. Find the two letter language code for the language website. Use the ISO 639-1 column on the list here: https://www.loc.gov/standards/iso639-2/php/code_list.php
2. Post a comment with the generation code, in the following format:
    ```
    gen "LANGUAGE CODE" "NAME OF WEBSITE" "WEBSITE URL"
    ```
    **Example for Read Comics Online:**
    ```
    gen "en" "Read Comics Online" "http://readcomics.website"
    ```

Resolves #101 
Resolves #98
Resolves #34
Resolves #57

### CODE REVIEW

**Comment by null-dev** [comment]
@inorichi I think this is ready for merge now. It's impossible to thoroughly test all the sources but I haven't found any more bugs during my testing.

**Comment by inorichi** [comment]
I've yet to test this before merging. This is a single extension, right?

**Comment by null-dev** [comment]
@inorichi Yep, I think it would be disastrous to maintain this as 20 different ones.

**Comment by null-dev** [comment]
@inorichi This PR is still ready to merge. The only reason I'm still adding commits is because some of these sources are unstable and keep going offline (so I have to remove them)...

**Comment by inorichi** [comment]
Yeah sorry, I was waiting to finish the extensions PR before merging this (I was still unsure about what to do for extensions with many sources) in case I added some incompatibility.

BTW, if you're not going to use any of the parsed methods, wouldn't it be better to inherit from `HttpSource` instead? You'd avoid all those `throw`.

**Comment by null-dev** [comment]
@inorichi Thanks for that catch, fixed! I also agree on waiting until the extensions PR is done.

**Comment by isaacraz** [comment]
Hi there could you please post the APK so I can add it to my tachiyomi without waiting for it to be merged? Thank you.

**Comment by null-dev** [comment]
@isaacraz http://dl.nulldev.xyz/tachiyomi-all.mmrcms-v1.2.1-debug.apk

**Comment by riedhows** [comment]
hello sir , can i ask , how to use this script to mymangareader cms ?

sorry i do not understand how to use it

**Comment by null-dev** [comment]
@riedhows This script allows you to add MyMangaReader CMS sites to Tachiyomi. If you have a MyMangaReader CMS site, please tell me and I will add it for you.

**Comment by CarlosEsco** [comment]
@inorichi I'll defer to you when you want to merge this.

**Comment by Sparh4wk** [comment]
@CarlosEsco well mangazuki extension is dead anyway.. and for new extension we need to wait for new website.. yet about 2 months ago, it was soon.. now its soon.. so I dont think that one extension for broken website counts..

**Comment by TonyToscana** [comment]
As mangazuki staff isn't saying anything about their new website I'm going to do the extension with the current temporary website.

**Comment by WiseBird** [comment]
@null-dev, what about tags? Can they be parsed in generic way also.? Without them filter looks empty.

**Comment by null-dev** [comment]
@WiseBird Yep, it's possible. Feature added.

**Comment by WiseBird** [comment]
@null-dev Thank you

**Comment by riedhows** [comment]
hi sir , can help me how to add new scrapper site for this cms ?
i don't know how to add more link scrapper from indonesian sites

thank you sir

**Comment by null-dev** [comment]
@riedhows This is a Tachiyomi extension. I can't help you add scraper sites
here.

**Comment by NeiRib** [comment]
If you add http://www.tumangaonline.com you can ignore all the other Spanish websites, because this is the largest and most complete that exists in Spanish

**Comment by null-dev** [comment]
@inorichi Are we able to merge this now?

**Comment by inorichi** [comment]
Yeah, sorry.

Do you want to add an icon for the extension first? I can't seem to find a logo though.

Also, can you give your opinion on my last comment at #169?

**Comment by null-dev** [comment]
@inorichi 

Whoops, I changed the app name to "Tachiyomi: My Manga Reader CMS (Many sources)" a couple days ago but forgot to reply.

As you've mentioned the CMS doesn't seem to have any icon associated with it. Should I put together an icon with an acronym? Maybe `MMR CMS` or `MMR`? Or maybe I can use the material `collections` icon as the extension icon to clarify that the extension has multiple sources?

**Comment by inorichi** [comment]
Hm... no clue. Do you have any idea @CarlosEsco ?

**Comment by CarlosEsco** [comment]
CMS seems fine

**Comment by null-dev** [comment]
Here is one with CMS:
src-cms
Here is another one from when I was experimenting around with multiple source logos:
untitled

I think the simple CMS one looks better TBH...

**Comment by CarlosEsco** [comment]
I agree CMS. Worst case someone opens an issue and we point them to CMS extension when it has the source

**Comment by null-dev** [comment]
@inorichi Icon added. Anything else? Squash?

**Comment by inorichi** [comment]
No need for that, GitHub has us covered!

**Comment by Leyshirtt** [comment]
Sorry sir, i already install this extension and try to open mangaid, when i open some chapter it take downloading like forever other manga still like that. 
My connection is stable i try another source and it's ok

**Comment by Kyranna** [comment]
@null-dev please add if possible
gen "pl" "Dracaena" "http://dracaena.webd.pl/czytnik/"

**Comment by null-dev** [comment]
@Kyranna Made a P.R. for it: https://github.com/inorichi/tachiyomi-extensions/pull/421

**Comment by MerradOklom** [comment]
gen "es" "Mangas" "https://mang.as"

**Comment by CarlosEsco** [comment]
Open a new issue and mention this site as addition to source. Posting in an old closed pull request makes this hard to track

**Comment by arkon** [comment]
Better yet, open a PR. :)

**Pull request merged**
