### PR TITLE
remove old apks for pr #1235

### PR DESCRIPTION
**Pull request by ZaneHannanAU**

### CODE REVIEW

**Comment by arkon** [comment]
Delete the older versions too.

**Comment by ZaneHannanAU** [comment]
I'm looking for them, and can't seem to find them.

I did

```shell
$ rm {apk,icon}/tachiyomi-en.man{gafox,gaplus,gago,gacow,hwahentai}*
```

as that should have removed them... but no idea on what's going on.

**Comment by ZaneHannanAU** [comment]
When I look at https://github.com/inorichi/tachiyomi-extensions/tree/repo/apk I see only one version of each; so it seems a little odd.

**Comment by arkon** [comment]
Oh, weird. I thought it kept the old versions too.

**Pull request merged**
