### PR TITLE
MangaHere update

### PR DESCRIPTION
**Pull request by CarlosEsco**
updated to match internal source

### CODE REVIEW

**Comment by inorichi** [comment]
Can you also update the version code and version name? Every change is supposed to have those increased, otherwise the FDroid repo won't show any update (or so I think).

**Comment by CarlosEsco** [comment]
Fixed and updating rest of pull requests.  You should consider making releases for the extensions-lib in github and using jitpack.  To pull the jar as a contributor i have no access to know which versions libs are on you bintray.

**Comment by inorichi** [comment]
It's here: https://bintray.com/inorichi/tachiyomi/extensions-library

**Comment by CarlosEsco** [comment]
Oh i guess im just dumb :).  I think i tired to go to dl.bintray,com directly and was wondering why it didnt work lol.

**Comment by inorichi** [comment]
I added a latest version badge to the readme of the library repo.

**Pull request merged**
