### PR TITLE
Remove old/obsolete APKs

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Remove old APKs as they are unnecessary.

### CODE REVIEW

**Comment by arkon** [comment]
Remove the corresponding icons too.

**Comment by AbdullahM0hamed** [comment]
My bad, should be done now.

**Comment by arkon** [comment]
I think the icons are still there?

**Comment by AbdullahM0hamed** [comment]
The changes seem to have reflected a doubled changed files count, but doesn't seem to be listing all the changed files. You can check https://github.com/AbdullahM0hamed/tachiyomi-extensions/tree/repo/icon to see that the icons have been removed.

**Pull request merged**
