### PR TITLE
Fix MangaPark image URLs and some code cleanup

### LINKED ISSUE #158: MangaPark issue: Broken covers in Latest
When browsing 'Latest', most of the covers are completely broken. This doesn't happen in 'Browse'.
screenshot_20180116-023953

### PR DESCRIPTION
**Pull request by null-dev**
Resolves #158

### CODE REVIEW

**Comment by inorichi** [comment]
Can you upgrade the version?

**Comment by inorichi** [comment]
F-Droid won't show updates if version code isn't upgraded. Sorry for not being clear enough last time :(

**Comment by null-dev** [comment]
@inorichi Yeah, I understood it clear enough. I have upgraded the version.

**Comment by inorichi** [comment]
I meant, version code too. You only upgraded version name, which will show a different version label but AFAIK F-Droid only uses version code to display updates

**Comment by null-dev** [comment]
@inorichi So `versionSuffix` = `versionName`?

**Comment by inorichi** [comment]
Only the last part. `libVersion` has the first two.

**Pull request merged**
