### PR TITLE
Feature/mangadex thumbs

### PR DESCRIPTION
**Pull request by Pavkazzz**
Now mangadex open all mangas for search thumbnail

Add some small fix to doesn't make request every time

### CODE REVIEW

**Comment by CarlosEsco** [comment]
This Lowers the cover image quality though right?

**Comment by Pavkazzz** [comment]
@CarlosEsco It's lowers in manga list screen, when you open manga, it's will be high quality again

**Comment by Pavkazzz** [comment]
Add new prefs to low quality thumbnails

**Comment by thu2468** [comment]
Is default setting on low or high?
also if i set setting to high in mangadex list of manga will it be in high or low? Same for when you open manga too?
Then there if you set setting to low. Will the mangadex list of manga be in low setting while you in the manga detail it will be high quality?

**Comment by CarlosEsco** [comment]
High is default. If you set it to low the browse/search/latest will be low quality. If you open a manga it usually replaces the low quality with hq

**Pull request merged**
