### PR TITLE
Add MangaStein to Madara

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Fixes https://github.com/inorichi/tachiyomi-extensions/issues/2863

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
Oh God, I really need to learn how to properly use git.

**Comment by Agayev033** [comment]
Where iş Mangastein ?
https://i.hizliresim.com/uuDrKf.png

**Comment by AbdullahM0hamed** [comment]
It seems I forget to the very crucial step of adding it to the list.

I seem to be forgetting a lot of things today. Will PR for it

**Comment by Agayev033** [comment]
Thnx bro i Love you <3

**Comment by rqumus78** [comment]
Mangastein still not added?

**Pull request merged**
