### PR TITLE
Update NANI? Scans extension to use their API

### PR DESCRIPTION
**Pull request by Dinokin**

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
I see that they changed domains, but is there a significant need to switch to parsing from their API vs HTML? Switching is going to break any favorited manga users have as well as their chapter lists.

**Comment by Dinokin** [comment]
Well the API should be more consistent since I don't plan to change anything there anytime soon. It also supports stuff like search by name, tag and id which the site doesn't support yet. As for the lost chapter list and favorites, it would break anyway because I plan to change some routes on that area soon.

**Comment by SnakeDoc83** [comment]
Ah, I see. I'd like to request 2 changes then:
* set `thumbnail_url` on `popularMangaParse()` and `latestUpdatesParse()` (in addition to where you already set it)
* one instance of SimpleDateFormat to use as a date parser

**Comment by Dinokin** [comment]
Done o7

**Comment by SnakeDoc83** [comment]
Thanks for the update.

Note: I bumped `versionId` since this won't be compatible with old favorites.

**Pull request merged**
