### PR TITLE
nsfw true added in query param

### PR DESCRIPTION
**Pull request by balagurusurendar**
#4050 
added nsfw=true in query param

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Should probably be an option?  To disable or enable it

**Comment by balagurusurendar** [comment]
yes, it needs to be an option
sorry I am not well versed in android & kotlin
for now, to make it work I added as query param by default.
in case you have a better idea you can go ahead & drop this pull & add your own change.
@CarlosEsco

**Comment by CarlosEsco** [comment]
If you at one of the other extensions with options like mangadex. You can see how the preference is made and used

**Comment by balagurusurendar** [comment]
I will check it out @CarlosEsco 
thank you for pointing it out.

**Comment by balagurusurendar** [comment]
@CarlosEsco 
added preference, please check it out

**Comment by CarlosEsco** [comment]
Looks good you need to update the build.gradle

**Comment by balagurusurendar** [comment]
version changed

**Pull request merged**
