### PR TITLE
Fix #5060 and #5040

### LINKED ISSUE #5040: [Source Request] <Mangareader.cc>
## Source Website
- Name: Mangareader.cc
- Link: http://mangareader.cc/
- Language(s): EN

## Other Details
Uploads Manga hwa hua.

### LINKED ISSUE #5060: [Bug] <MangaFast>: <thumbnail fix + new logo>
## Device information
- Tachiyomi version: latest
- Android version: 10

## Source information
- Name: Mangafast
- Extension version: latest

so currently mangafast thumbnail is 9:16 due to extra parameter fetched during image retrevial 
`https://i0.wp.com/mangafast.net/img4/2020-09-24/2002/thumbnail-the-story-of-an-onee-san-who-wants-to-keep-a-high-school-boy-manga.jpg?resize=300,180&quality=70`

its not an appropriate size

also change logo
to this 
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/5659639/ic_launcher.2.zip)

### PR DESCRIPTION
**Pull request by antonycaporossi**
Fix #5060 and update ic_launcher icon for MangaFast (thx to @as280093 for the archive with icon files)
The thumbnail problem was in the "Latest" page.

Close #5060

--------------------

In all-paprika Extension
Remove MangaWindow.club
Add MangaReader.cc

Close #5040

### CODE REVIEW

**Comment by Riztard** [comment]
isnt this push same as this #5062

**Comment by antonycaporossi** [comment]
Yes, sorry for double pull request. I made a mistake with branches.

**Comment by CarlosEsco** [comment]
So why are you leaving both up?  close 1, edit the another to say everything its doing

**Comment by antonycaporossi** [comment]
Fixed. Sorry, first time contributing on Github. Hope everything is fine now

**Pull request merged**
