### PR TITLE
[Add] ToonManga

### LINKED ISSUE #1753: [Source Request] Toonmanga
### Source Website
Website can be found at https://toonmanga.com/

### Other Details

English language. there are manga which chapter not available in any other manga, such as "kitty boy" which reach chapter 65.

### PR DESCRIPTION
**Pull request by happywillow0**
Closes #1753

### CODE REVIEW

**Comment by happywillow0** [comment]
[mangakomi ](http://mangakomi.com/) is down, should we take it out?

**Comment by samanta-widjaja** [comment]
thanks happyillow

**Comment by arkon** [comment]
Can you resolve the conflicts?

**Comment by happywillow0** [comment]
Oops. I didn't realize there was any. I'll take a look when I have a chance .

**Pull request merged**
