### PR TITLE
Add NewToki (Korean Source)

### PR DESCRIPTION
**Pull request by DitFranXX**
Another korean source.

### CODE REVIEW

**Comment by DitFranXX** [comment]
Travis build error is not this PR problems that caused by #784 which fixed on #787 (It also appears on #786).

Is possible to build again? or skip checks and merge this.

**Comment by DitFranXX** [comment]
Force pushed to rebased commit

**Comment by as280093** [comment]
Hey you are missing the icons

**Comment by as280093** [comment]
[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2845501/res.zip)

**Comment by as280093** [comment]
Icons were missing so i provided in below complete res folder


[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2845501/res.zip)

**Comment by DitFranXX** [comment]
Icon added. Thanks to @as280093

**Pull request merged**
