### PR TITLE
Add more brazilian sources

### LINKED ISSUE #70: CentralDeMangas
Please add brazilian(Portuguese) source: http://centraldemangas.net.br/

### LINKED ISSUE #71: YesMangas
Brazilian source: https://yesmangas.net

### LINKED ISSUE #583: Source Request
Hi. I have a suggestion. I like read manhua. Can you create an extension with this site https://saikaiscan.com.br

### PR DESCRIPTION
**Pull request by alessandrojean**
- Add [CentralDeMangas] source (closes #70);
- Add [YesMangas] source (closes #71);
- Add [SaikaiScan] source (closes #583 and #674).

[CentralDeMangas]: http://cdmnet.com.br/
[YesMangas]: https://yesmangasbr.com/
[SaikaiScan]: https://saikaiscan.com.br/

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Are the novels images? Cause tachiyomi doesn't support novels

**Comment by ESM96** [comment]
No.. Is there any way to solve this?

**Comment by ESM96** [comment]
Já que te chamas Carlos penso que és brasileiro ou português.
Estive a procurar e o site https://mangahost1.com usa imagens. Poderiam adicionar esta fonte?

**Comment by CarlosEsco** [comment]
No tachiyomi is not a e-reader

**Pull request merged**
