### PR TITLE
Wpmangastream fixes

### LINKED ISSUE #4428: [Bug] <Kiryuu (id)>: <java.lang.string...... on a null object reference>
---

## Device information
- Tachiyomi version: v0.10.5
- Android version: 8.1

## Source information
- Name: kiryuu (id)
- Extension version: v1.2.2

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
refresh new chapter and show chapter

### Actual behavior
i tried backup and restore but error it's happen to all manga
Screenshot_2020-09-23-20-42-57-08
 

## Other details
before this bug,have another bug = new chapter didn't show on Updates

### LINKED ISSUE #4461: [Bug] <https://readkomik.com/>: <java error>
---

## Device information
- Tachiyomi version:  App version: 0.10.5-2734 
- Android version: 10 (SDK 29)

- Device brand: Xiaomi
- Device model: Mi 9T

## Source information
- Name: https://readkomik.com/
- Extension version:  wp mangastream 1.2.24

Different Kings (Readkomik (EN)): Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference

source is broken in app
in webview work

Screenshot_2020-09-28-18-58-40-227_eu kanade tachiyomi debug

Screenshot_2020-09-28-19-03-22-726_eu kanade tachiyomi debug

### LINKED ISSUE #4593: [Bug] Asura Scans (java.lang.string) Error
### Device information

Tachiyomi version: 0.10.5

Android version: 10

### Source information

Name: Asura Scans 

Extension: WPMangastream 1.2.25

### Steps To Reproduce

1.Go to Browse Section

2.Choose Asura Scans

3.Choose any manga and try to update it

### Expected behavior

It should show new chapters

### Actual behavior
It shows java.lang.string Error
Screenshot_2020-10-12-22-33-20-731_eu kanade tachiyomi

### Other details

Webview works fine

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Closes #4593 
Closes #4461
Closes #4428

### CODE REVIEW

**Comment by arkon** [comment]
Psst

**Comment by jobobby04** [comment]
LOL

**Comment by AbdullahM0hamed** [comment]
Oh.

**Comment by CrepeTF** [comment]
:risitas2:

**Pull request merged**
