### PR TITLE
Acomics

### PR DESCRIPTION
**Pull request by Pavkazzz**
Add new source - https://acomics.ru

### CODE REVIEW

**Comment by CarlosEsco** [comment]
@as280093 do you want to do nicer icons?

**Comment by as280093** [comment]
wait ✋ i will make one ☝

**Comment by as280093** [comment]
Here is the res Folder:
[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2849761/res.zip)


image:
web_hi_res_512

**Comment by Pavkazzz** [comment]
@as280093 It's really amazing, thx

**Comment by as280093** [comment]
> @as280093 It's really amazing, thx
for any other new extension message me on discord : as280093#5472

**Pull request merged**
