### PR TITLE
Update Gradle, Kotlin, and enable parallel builds

### PR DESCRIPTION
**Pull request by arkon**
Requires the latest stable version of Android Studio (3.4).

### CODE REVIEW

**Comment by inorichi** [comment]
I wouldn't upgrade kotlin too much as the bytecode might be incompatible with the main app. Or at least test everything is still ok, but there's not much to gain from a kotlin update here.

**Comment by inorichi** [comment]
Although I'm more worried about the new D8 rather than kotlin updates.

**Comment by null-dev** [comment]
Upgrading Kaitlin may be a bad idea: https://stackoverflow.com/questions/55708793/switch-to-kotlin-1-3-30-breaks-hashcode-only-on-android-api-21

**Comment by arkon** [comment]
Welp, let's hold off then.

**Comment by inorichi** [comment]
Parallel builds are probably a good idea, tho. Even more here considering the amount of modules.

**Pull request closed without merging**
