### PR TITLE
[Ru] Mangalib. Fix 403 image without referer

### PR DESCRIPTION
**Pull request by Pavkazzz**
subj

### CODE REVIEW

**Comment by Pavkazzz** [comment]
@arkon @SnakeDoc83 take a look pls, many users complaint in rus forum

**Comment by AriaMoradi** [comment]
duplicate of #5092

**Comment by AriaMoradi** [comment]
closes #5092

**Comment by Kugumin** [comment]
Waiting for merge

**Comment by AriaMoradi** [comment]
I can't test this because they blocked my IP for some reason. And it's the first time I was visiting the site.

**Comment by Kugumin** [comment]
I may test it if someone will send me compiled 1.2.25 Mangalib extension

**Comment by Pavkazzz** [comment]
Next fixes in https://github.com/inorichi/tachiyomi-extensions/pull/5112

**Pull request merged**
