### PR TITLE
Mangadex: Use preferences to specify domain

### PR DESCRIPTION
**Pull request by ZaneHannanAU**
This is future proofing so that if org goes down once more, or if more domains are added, it can be changed (default) or set specifically through the defaults in updates.

- [x] Built
- [x] Tested
- [ ] Ready to merge

### CODE REVIEW

**Comment by arkon** [comment]
Tbh this seems overkill.

**Comment by ZaneHannanAU** [comment]
tbh probably is
but avoids issues later on and less version bumps overall

**Comment by ZaneHannanAU** [comment]
Hrmm. Seems to only show three settings.

**Comment by ZaneHannanAU** [comment]
Whatever. Current one works for now. May be worth ensuring we're back on mangadex.org & mangadex.org

**Comment by happywillow0** [comment]
> Hrmm. Seems to only show three settings.

What Android version are you on? Code got updated to Android X which is a separate code block.

**Comment by ZaneHannanAU** [comment]
Android 9, Google Pixel (original)

**Pull request closed without merging**
