### PR TITLE
Add MangaSwat Warning

### PR DESCRIPTION
**Pull request by happywillow0**
Addresses #2180

Checks headers for sucuri bypass (similar to cloudflare). 

If not bypassed, prompts user to open webview. This attempts to replace error "no results found".

### CODE REVIEW

**Comment by happywillow0** [comment]
Not currently. 

Manual search, you have to open browse
Everything else I suppose would silently fail as with what is happening currently. 

One problem is that Sucuri doesn't give a http error code so it will only fail at the any of the page parsing steps. 

Do you want me to try to insert it into more places?

I'm looking at refactoring the code but I don't want to break global search with a thrown exception.

**Comment by happywillow0** [comment]
Update: 

All functions except for search should have the check now. Global search will fail cleanly and silently similar to Mangadex with no results. Any other methods will result in the pop up message.

**Comment by arkon** [comment]
I was going to suggest overriding the network client to have an interceptor to do the check. Might still be a good idea? I'm fine with the current implementation too.

**Comment by happywillow0** [comment]
I had to learn how to build a custom interceptor but here we go.

**Pull request merged**
