### PR TITLE
Issue templates

### PR DESCRIPTION
**Pull request by hXtreme**
Add templates for issues to make it easier to report issues.

__Might need significant help from reviewers to polish the templates.__

### CODE REVIEW

**Comment by as280093** [comment]
Is source request & meta request
Required in Extension Repo

**Comment by hXtreme** [comment]
__Source Request:__ Yes, It would be used by people suggesting new sources while feature requests should be about adding things like sorting, tags... to a source.  
__Meta:__ I don't know.

**Comment by as280093** [comment]
Ohh lol it's feature request does it's required,

**Comment by hXtreme** [comment]
@as280093 I don't understand what you're saying.

**Comment by arkon** [comment]
I think we only really need templates for source requests and bugs. The other scenarios don't really need templates.

**Comment by hXtreme** [comment]
Not even feature request?  

For example:

Please add filter for tags on source X...

**Pull request merged**
