### PR TITLE
Foolslide - remove HelveticaScans, ShoujoSense, ShoujoHearts

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Helvetica's website has been gone for almost 2 months.

ShoujoSense removed their reader.

ShoujoSense hasn't added anything in 6 months and their reader is inaccessible.

### CODE REVIEW

**Comment by moffeemoffee** [comment]
I seem to be able to access Helvetica Scans's website though: https://helveticascans.com/

**Comment by SnakeDoc83** [comment]
The site came back a day or two after it was removed from Tachi :/

They're still not keeping it as up to date as what they post on MangaDex
though.

**Comment by iZN1337** [comment]
Hello, I'm the one managing the web stuff of Helvetica Scans. We've recently moved out of a web host to a dedicated server, we'll be ensuring it's kept alive as long as possible. Recent chapters haven't been up to but they will be soon enough, our staff were mainly focusing on releasing it on MangaDex first due to the site becoming unstable. 

So in short, it is alive permanently. We'll be releasing everything there.

**Comment by SnakeDoc83** [comment]
I'll go through the Foolslide's sources today, see how they're doing, and
open a PR to add Helvetica back.

**Pull request merged**
