### PR TITLE
Add icons for HQDragon

### PR DESCRIPTION
**Pull request by alessandrojean**
Add missing icons for #1516.

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
as280093 made some icons last night that I was going to add today.

**Comment by alessandrojean** [comment]
I didn't see anything about this icon, so I made one in the generator. Do you want me to close this PR or is it okay to use this new icon?

**Comment by as280093** [comment]
Yup as this or is missing Gradle file too

**Comment by as280093** [comment]
Here's the icon raw
image

**Comment by alessandrojean** [comment]
Wow, nice icon. I will update to it and update the Gradle file.

**Pull request merged**
