### PR TITLE
[WIP] Anibe!manga source

### PR DESCRIPTION
**Pull request by deissh**
new source from issue #1217

### CODE REVIEW

**Comment by as280093** [comment]
use this icon, i can't find the website or i could have made icon based on favicon or icon
till then use thia
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3316659/ic_launcher.4.zip)

**Comment by zagrib** [comment]
I always read manga online at https://mangatensei.com

**Comment by SnakeDoc83** [comment]
@deissh I have a working extension for Anibe if you're interested.

**Comment by deissh** [comment]
@SnakeDoc8, of course
I just don't have a lot of personal time right now to finish this pr

**Comment by arkon** [comment]
Superseded by #1272

**Pull request closed without merging**
