### PR TITLE
Anibe (Russian extension)

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Filling request: https://github.com/inorichi/tachiyomi-extensions/issues/1217

@as280093 I'll take some icons when you have the time.

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
I just realized the guy who posted the request also has an open pull request for this.  I see there's icons too.  Well, I'll leave this open for now, sort it out later.

**Comment by as280093** [comment]
as this is a api based and i can't find actual website the one you used is fine but if you have actual website i can make based on favicon or logo

**Comment by MerradOklom** [comment]
@as280093 apparently Anibe is an app: https://github.com/deissh/anibe.app
And they get the manga from https://shakai.ru
I hope it help you

**Comment by as280093** [comment]
ok so as they have a app and they have same as what you used so its ok

**Comment by deissh** [comment]
> @ as280093, видимо, Anibe - это приложение: https://github.com/deissh/anibe.app
> И они получают мангу с сайта [http://shakai.ru/.](http://shakai.ru/)
> Надеюсь, это поможет вам
> 
> Изменить: я только что заметил, что фактический разработчик создал другой PR

I answered in the original PR (my) that I have no time to finish

**Comment by deissh** [comment]
> @as280093 apparently Anibe is an app: https://github.com/deissh/anibe.app
> And they get the manga from http://shakai.ru/
> I hope it help you
> 
> Edit: I just noticed the actual developer created the other pr

not really, 90% images get from shakai.ru
but some manga from my s3 bucket with cdn

**Comment by SnakeDoc83** [comment]
Unless I've overlooked something, this extension should be good to go.  So since you're fine with it I'll ask that someone review this PR and if it passes you can close yours.

**Pull request merged**
