### PR TITLE
HQDragon - new extension

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1341

Just needs icons

### CODE REVIEW

**Comment by arkon** [comment]
Whoops merged before the icons were added. Please open another PR for that... 😅

**Comment by SnakeDoc83** [comment]
Ha, no problem

**Comment by willblackmusic** [comment]
it's only showing 10 comics

**Comment by webnamoro** [comment]
You need search for titles

**Pull request merged**
