### PR TITLE
Madara add Customizable source

### PR DESCRIPTION
**Pull request by Riztard**
yoink from foolslide ext with little change
<table>
<td></td>
<td></td>
<td></td>
</table>

### CODE REVIEW

**Comment by arkon** [comment]
Considering there's a billion Madara sites, is this actually useful? It'd break if you ever favorite something and then change the domain.

**Comment by Riztard** [comment]
not sure why it exist on foolslide too, was it for temporary? 🤔

**Comment by jobobby04** [comment]
Foolslide is easily self hosted

**Comment by Riztard** [comment]
for madara then use for temporary? 
image

**Comment by arkon** [comment]
No, I'm going to reject this since the usecase doesn't quite make sense.

**Comment by Riztard** [comment]
rip

**Comment by CrepeTF** [comment]
Good

**Pull request closed without merging**
