### PR TITLE
TurkceManga Problem Solved

### PR DESCRIPTION
**Pull request by Agayev033**

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
Testing TurkceManga before and after adding a `www` prefix - and it doesn't seem to get rid of the 401 error in Tachiyomi itself, although the site appears in the webview (which it didn't seem to before)

**Comment by Agayev033** [comment]
What can i di bro?
I am not good at programming.

**Comment by SnakeDoc83** [comment]
@Agayev033 Search works; so I'm guessing you need to override `popularMangaRequest()` and `latestUpdatesRequest()`.

**Comment by Agayev033** [comment]
Okey thnx

**Comment by Agayev033** [comment]
Okey thnx

**Pull request closed without merging**
