### PR TITLE
ReadMangaToday update

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1485

Fixed the issue with chapters, added getting thumbnails for popularMangaRequest, made a few tweaks to get rid of some warnings.

### CODE REVIEW

**Comment by Black-Seraph** [comment]
Seems to still be broken here.

**Comment by SnakeDoc83** [comment]
Which chapters of which manga are you having an issue with?

**Comment by Black-Seraph** [comment]
Attack on Titan, Chapter 121.

But any chapter I don't have a local copy of works for testing this really.

**Comment by SnakeDoc83** [comment]
It's working for me, but I have noticed it can be a little wonky at times.  Are you using 1.2.8 of the extension?  I ask because this is the PR for 1.2.7.  If you are on the latest version, try back backing out of the chapter, wait a few seconds, and open it again.  Beyond that you can try talking with the folks on discord and maybe something will come to light that will lead to an improvement for the extension.

**Pull request merged**
