### PR TITLE
Add TMOHentai #924

### PR DESCRIPTION
**Pull request by edgarMejia**

### CODE REVIEW

**Comment by as280093** [comment]
Res folder here

https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/tmohentai.com/res

ic_launcher

**Comment by edgarMejia** [comment]
Thanks!

**Comment by arkon** [comment]
Quick question, how similar is this to the other TMO extension(s)? Would it make sense to combine them?

**Comment by edgarMejia** [comment]
@arkon this in particular (TMOHentai) is only similar in the search request (a little similar), I don't think it's convenient to combine it with the others (I don't think it's a good idea to put a hentai extension with the main), but "TuMangaOnline" and "LectorManga" are identical, we should combine them.

**Pull request merged**
