### PR TITLE
 Fix "Page List Empty" with Randomized Suffix (KissManga)

### PR DESCRIPTION
**Pull request by i404788**
The suffix hasn't changed since my last pull request so feel free to wait on this pull request.

I've tested it with https://gist.github.com/i404788/a1a53c1c2d269de989551515b44dfb94
The previous solutions didn't work with the test program, however this does seem to work.

### CODE REVIEW

**Comment by armangido** [comment]
This won't fix the cloudflare issue with kissmanga they seems giving Acesss Denied to Tachiyomi users.

**Comment by i404788** [comment]
@armangido Indeed it doesn't, however I haven't seen that issue yet myself

**Comment by SnakeDoc83** [comment]
As an FYI, they've been intentionally banning Tachi users all month.  If people are getting banned (access denied) right now it's more than likely a continuation of that policy.

**Comment by armangido** [comment]
Seems issue is coming from the cloudflare libraries

**Pull request merged**
