### PR TITLE
Add Inkr (all the code is from MR)

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
You will recognise the code - it's from the old MR extension.

Worked after some slight modifications (apiUrl and /pagesv3 instead of /pagesv2) 

Here's to a new era of inkr memes.

### CODE REVIEW

**Comment by arkon** [comment]
Do the filters need to be updated?

**Comment by AbdullahM0hamed** [comment]
Filters work. Rank doesn't atm though - should I remove that?

**Comment by arkon** [comment]
Yeah, remove whatever doesn't work. Do the genres still work?

**Comment by AbdullahM0hamed** [comment]
Genres work fine. Some of them return no results (which I've chalked down to it having a smaller library, but I'll guess I'll remove whatever returns nothing there too)

**Comment by AbdullahM0hamed** [comment]
Filters have been updated.

**Pull request merged**
