### PR TITLE
Scantrad - new extension

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Just needs icons.

Closes https://github.com/inorichi/tachiyomi-extensions/issues/414

### CODE REVIEW

**Comment by as280093** [comment]
[scantad.zip](https://github.com/inorichi/tachiyomi-extensions/files/3674683/scantad.zip)
@SnakeDoc83

**Comment by SnakeDoc83** [comment]
Thanks

**Comment by Rediowz** [comment]
Thanks ! You guys are the best

**Comment by Flavien06** [comment]
Stop working, http error 403

**Pull request merged**
