### PR TITLE
Manhwas Men support

### LINKED ISSUE #4246: [Source Request] manwhas.men
well cuz secret class and other good 18+ manhwa is more fast for new chp so i hope tachi can add this site to madara extension make a new extension 
## Source Website
- Name: manhwa.men
- Link: https://manhwas.men/
- Language(s): english ,raw,spanish

### PR DESCRIPTION
**Pull request by whyimdoingthis**
Hello.

I added Manhwas Men support to the [MMRCMS](https://github.com/inorichi/tachiyomi-extensions/tree/master/src/all/mmrcms).
I hope I did it right: I can see latests manga and do search.

But I couldn't understand how do you execute the Generator https://github.com/inorichi/tachiyomi-extensions/blob/004b12abaff5ac19ead709c4adeec77651220487/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/Generator.kt#L337
So I generated the code for ManhwasMen manually and violated the rule `Do not modify generated file`.
https://github.com/inorichi/tachiyomi-extensions/blob/004b12abaff5ac19ead709c4adeec77651220487/src/all/mmrcms/src/eu/kanade/tachiyomi/extension/all/mmrcms/GeneratedSources.kt#L3

If you know how to run Generator, please let me know.

Closes #4246

### CODE REVIEW

**Comment by CarlosEsco** [comment]
If you didnt run generator, did you hand add that section in the generated file?

**Comment by CarlosEsco** [comment]
There is no guarantee that the next time it generates that it works.  You should be able to just run the generator in the ide

**Comment by whyimdoingthis** [comment]
@CarlosEsco I'm agree with you. Sorry for being dumb, but how am I supposed to run `main()` method inside the android.

- I cloned the repo.
- Openned it in the latest android studio
- Did some changes in the codebase
- Successfully build the project
- Uploaded extension to the device using instructions from [the contrib](https://github.com/inorichi/tachiyomi-extensions/blob/master/CONTRIBUTING.md#running)

May be I didn't install some plugin to the Android Studio? But I don't understand how to execute this Generator.

screenshot

Again, sorry.
Thanks a lot for your work.

**Comment by CarlosEsco** [comment]
You don't run it as an android app.  You should be able to right click the function and run it

**Pull request merged**
