### PR TITLE
RawLH: Update page list parse

### LINKED ISSUE #1501: RawLH is only displaying credit pages
BUGS:
RawLH only showing single page of credit page only

Tachiyomi 0.8.4 Build 13 April 2019 9:16 pm
RawLH 1.2.9

### PR DESCRIPTION
**Pull request by rama982**
Fix #1501

Fyi, when i updating code they just changed chapter img url mechanism.
this is latest changes on the site.

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
`document.select("script")`  
There are dozens of scripts you're selecting by using "script" on its own.  You could be more specific with something like `document.select("script:containsData(imgsrc)")`

`if (encodedUrl != "")` 
If there are cases where encodedUrl would be empty, shouldn't there be an else statement to go with this?  If there are no cases where encodedUrl is empty, then why check?  Might be something to consider.

**Comment by rama982** [comment]
@SnakeDoc83 thanks for review, i will recheck the code.

**Comment by rama982** [comment]
i already update the code and tested with > 5 titles manga and all work good.

**Comment by rama982** [comment]
just when this PR merged they updated the mechanism again, so better wait some days until they not changed stuff or update again?

**Pull request merged**
