### PR TITLE
Fix manhuaren thumbnail url

### PR DESCRIPTION
**Pull request by geniusgordon**

### CODE REVIEW

**Comment by arkon** [comment]
Would've been nice to see this use `firstOrNull`

**Comment by geniusgordon** [comment]
@arkon do you mean something like this
is there a better way so I don't need to call `getString` twice
```
val key = arrayOf(
    "mangaCoverimageUrl",
    "mangaPicimageUrl",
    "shareIcon"
).firstOrNull {
    obj.getString(it) != ""
}
thumbnail_url = obj.getString(key)
```

**Comment by arkon** [comment]
You can do something along the lines of this to avoid eager evaluation (just going off the top of my head, so it might be wrong):

```kotlin
thumbnail_url = listOf(
      "mangaCoverimageUrl",
      "mangaPicimageUrl",
      "shareIcon")
    .asSequence()
    .map { obj.optString(it) }
    .firstOrNull { it != "" }
```

**Comment by geniusgordon** [comment]
@arkon thanks for the advice, my original code looks so redendant 😂

**Pull request merged**
