### PR TITLE
add-matakomik

### LINKED ISSUE #3294: [Source Request] matakomik
### Source Website
- Name: matakomik
- Link: https://matakomik.com/
- Language(s): bahasa indonesia

### Other Details
The most complete list of Indonesian manga in my opinion.

### PR DESCRIPTION
**Pull request by kikuKeii**
close #3294

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
Instead of creating a separate extension, this should be added to WP-Mangastream.

**Comment by kikuKeii** [comment]
what if both , make a separate extension and add it to WP-Mangasteram. Make a choice for users who don't want to install wp-mangasteram?

**Comment by SnakeDoc83** [comment]
Doing that would mean you need to maintain both; so if something breaks or needs to be changed you have to do it twice.

**Comment by CarlosEsco** [comment]
Yea that won't get merged. Put it in wp.

**Comment by SnakeDoc83** [comment]
Closing in favor of https://github.com/inorichi/tachiyomi-extensions/pull/3311

**Pull request closed without merging**
