### PR TITLE
New Hatigarm Scans extension

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Hatigarm is currently in the Foolslide extension but it's been 404ing for 2 weeks or so.  Having checked their website, it doesn't appear to be using the Folslide reader any longer.  That being the case I've got this stand alone extension for Hatigarm going.

The search function works but may need to be updated at some point.  Their website's search appears to only give results with JSON.  I spent a little time looking in to using gson to parse the results but ultimately went a different direction.  Their website has an open directory listing their manga so I'm just searching through the titles in the extension itself.  That said, open directories don't always stay open forever; but it works for now.

### CODE REVIEW

**Comment by Vesnyx** [comment]
Well, this is super awkward. I've already pushed the working version since they switched to MMR-CMS now. I'm not sure if the search function still works, but everything else is already taken care of. :(

**Comment by as280093** [comment]
[ic_launcher (1).zip](https://github.com/inorichi/tachiyomi-extensions/files/3280358/ic_launcher.1.zip)
 use this icons as the one used are square rather then rounded square

**Comment by SnakeDoc83** [comment]
Ha ha, yeah, I saw your push right after I made mine.  I didn't realize MMR would cover Hatigarm's current website layout.  Oh well.

**Comment by arkon** [comment]
Sorry, looks like this isn't needed. 😥

**Pull request closed without merging**
