### PR TITLE
MangaBox - MangaOnl update

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1987

### CODE REVIEW

**Comment by NotTsunami** [comment]
Awesome, was just looking at the site myself, but you beat me to it!

**Comment by SnakeDoc83** [comment]
Yeah, they just changed some of their selectors; except they're not site-wide.  So there's a mix of old selectors and new ones, which always seems silly.

**Comment by happywillow0** [comment]
I don't think this isn't actually a change in selectors. It should be the same as kakalot where some manga entries are redirecting to the manganelo url. (I'm not sure why they are doing that).

**Comment by SnakeDoc83** [comment]
No, in this case it's new selectors for some manga.

**Comment by NotTsunami** [comment]
> I don't think this isn't actually a change in selectors. It should be the same as kakalot where some manga entries are redirecting to the manganelo url. (I'm not sure why they are doing that).

Actually, this is right. Search Trinity Seven, click on the first result on the website and it redirects to manganelo.

**Comment by SnakeDoc83** [comment]
Fair enough, different selectors because it's a different site.

**Pull request merged**
