### PR TITLE
Fix readcomicstv

### PR DESCRIPTION
**Pull request by j2ghz**
Needs testing

### CODE REVIEW

**Comment by j2ghz** [comment]
The site does not exist in both .tv and .website
Not sure whether to wait for a clone to appear or just remove it

**Comment by j2ghz** [comment]
It seems it's up again

**Comment by inorichi** [comment]
Still WIP?

**Comment by j2ghz** [comment]
The site is still up, so it can be merged.

**Comment by voythas** [comment]
It doesn't seem to work anymore. Catalogue returns 404.

**Pull request merged**
