### PR TITLE
Add ComicLatest

### LINKED ISSUE #3218: [Source Request] ComicLatest
### Source Website
- Name: ComicLatest
- Link: https://comiclatest.com/
- Language(s): English

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Closes #3218

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
I find it funny that your minor edit is for an issue of language but you didn't notice you missed bumping the gradle version.

**Comment by AbdullahM0hamed** [comment]
😂😂😂😂😂😂😂😂

**Comment by TheWrightStuff1994** [comment]
Search doesn't work... please quick fix! Also can you also also fix it so you can search for authors?

**Comment by AbdullahM0hamed** [comment]
I have no idea how that got past me. You should open an issue for it btw. I'll look into it in a bit.

**Pull request merged**
