### PR TITLE
Add Viz Shonen Jump

### LINKED ISSUE #2678: [Source Request] Viz Shonen Jump
### Source Website
Website can be found at [www.viz.com/shonenjump](https://www.viz.com/shonenjump)

### Other Details
It's a limited version of MangaPlus by Shueisha (as Viz only offers SJ), except the image quality is *MUCH* better. (Shueisha has ~150KB per page, Viz has ~400KB). 

Although, it seems to be available only for a [few countries](https://www.viz.com/company-faq), can't confirm as I can just access the manga chapters for free.

Would be great if support can be added for this :smiley:

### PR DESCRIPTION
**Pull request by alessandrojean**
Finally closes #2678.

I think in most of the mangas the pages are unscrambled correctly, but a little parcel of the mangas have [some issues](https://imgur.com/EsYeOij) (I only faced this on Astra Lost in Space).

I had to use the `ExifInterface` from old `android.support` because the `androidx` one gives me some warnings.

Thanks to @iamkroot and @TheUnlocked for the help!

### CODE REVIEW

**Comment by CarlosEsco** [comment]
What was the warnings in the androidx?

**Comment by alessandrojean** [comment]
That I have to add some flags to the compiler, but even when I tried to add it didn't work for some reason.

**Comment by arkon** [comment]
The `android.useAndroidX` flag? What didn't work after setting it?

**Comment by alessandrojean** [comment]
Yep, I don't remember the error, but I can try to use it again later.

**Comment by alessandrojean** [comment]
For some reason, it works now, but I am not sure if the `android.useAndroidX=true` is in the right file.

**Comment by arkon** [comment]
Do you mind checking if this works in 0.8.5 (which doesn't use AndroidX) too? It doesn't matter too much if it doesn't, but it's be good to know.

**Comment by alessandrojean** [comment]
I will test it.

**Comment by alessandrojean** [comment]
It's working as expected :)

**Comment by TheUnlocked** [comment]
I managed to get it to work for the premium chapters if the user logs in with the web interface (as well as some fixes to the selectors). I'll make a PR to your fork.

**Comment by alessandrojean** [comment]
I marked this now as WIP because I and @TheUnlocked are working into adding the support to locked chapters in my fork.

As soon as we finish it, I will tell it's ready to merge.

**Comment by alessandrojean** [comment]
It should be ready to merge now :)

**Pull request merged**
