### PR TITLE
Add ManManga Extension

### PR DESCRIPTION
**Pull request by waptik**
This is the first version of Man Manga extension #1296.
For now, you can only view list of mangas on the first page(search, latest and popular).
Next page contents are being pulled from a javascript file(quite complicated to understand).
I'll try and see if i can fix it in the next version.
For now enjoy it. @joseph619

### CODE REVIEW

**Comment by SnakeDoc83** [comment]
You're going to have to take another look at your PR, there's no need to change 311 files to add one extension.

You can access additional pages for popular manga with https://m.manmanga.com/category?sort=heat&page=$page if you don't want to get deep in to how they're using JSON.  You can probably add &pages=$page for latest and searches too.

**Comment by waptik** [comment]
311 changed files occurred when i was i did a pull upstream and trying to fix merge conflicts in the process. So how can i fix this? It's my first time contributing to a popular OSS project.

`&page=$page` worked for searches, latest and popular when i was playing their urls. But i wasn't sure if i should use that approach. Thanks for that.

**Comment by joseph619** [comment]
Thanks for the extension waptik ! Right now, the cover images and chapters are not loading, it says 'No chapters found'.

**Comment by waptik** [comment]
> 
> 
> Thanks for the extension waptik ! Right now, the cover images and chapters are not loading, it says 'No chapters found'.

where did you get the apk file from?

**Comment by joseph619** [comment]
> > Thanks for the extension waptik ! Right now, the cover images and chapters are not loading, it says 'No chapters found'.
> 
> where did you get the apk file from?

Here

https://github.com/inorichi/tachiyomi-extensions/raw/991424158b6a1993fdb8f0a44aa1ea02f2e57fcb/src/en/manmanga/release/tachiyomi-en.manmanga-v1.2.1-release.apk

**Comment by waptik** [comment]
> 
> 
> > > Thanks for the extension waptik ! Right now, the cover images and chapters are not loading, it says 'No chapters found'.
> > 
> > 
> > where did you get the apk file from?
> 
> Here
> 
> https://github.com/inorichi/tachiyomi-extensions/raw/991424158b6a1993fdb8f0a44aa1ea02f2e57fcb/src/en/manmanga/release/tachiyomi-en.manmanga-v1.2.1-release.apk

Sorry about. That was the first test file. It doesn't work. Here's the latest debug file: https://dropbox.com/s/oyimgrnzmtjqfej/tachiyomi-en.manmanga-v1.2.1-debug.apk?dl=0

**Comment by joseph619** [comment]
> Sorry about. That was the first test file. It doesn't work. Here's the latest debug file: https://dropbox.com/s/oyimgrnzmtjqfej/tachiyomi-en.manmanga-v1.2.1-debug.apk?dl=0
> 
> Edit: unistall the one you have before installing this one.

Thanks. There are only 15 manga on the browse page, and cover images still don't load automatically (I have to pull and refresh for them to load). Also, search function appears to be broken. This manga below named 'Strange Mirror' for example doesn't appear in search.

https://m.manmanga.com/detail/2BR95zwXj8a

**Comment by SnakeDoc83** [comment]
> 
> 
> 311 changed files occurred when i was i did a pull upstream and trying to fix merge conflicts in the process. So how can i fix this? It's my first time contributing to a popular OSS project.

It looks like the issue was with your 2nd commit, whatever you did on that one changed 311 files and was the reason you had the conflict you tried to fix with your 6th commit.  I don't know if you get can this straightened out with a rebase, rollback, or some other method.  If you can't figure it out or find someone to guide you, the last resort would be to make sure you have your work saved locally to your PC, delete your current repo, reclone, recommit, and then open a new PR.

**Comment by waptik** [comment]
I think the image issue is due to the fact that it's been taken from the
background image on the site.
I explained in my first post that for now it only fetches the first. For
your search issue, trying searching directly from the site and let me if
you can find it.

**Comment by waptik** [comment]
Ok thanks, I'll follow your suggestions.

**Pull request closed without merging**
