### PR TITLE
Add ComiCake support

### PR DESCRIPTION
**Pull request by chocolatkey**
Adds support for sites using ComiCake. All essentials work

# TODO

- [ ] Filters
- [x] Deduplicate comics in latest view
- [ ] Icon

### CODE REVIEW

**Comment by chocolatkey** [comment]
@einstein95 I swear I unchecked those... fixed

**Comment by einstein95** [comment]
Well, you removed it in de7cddb674912ac0027637b569f019faef69a362 and then added it back in 72904eeb51bac52570d3108cf220065538f9b64b :thinking:

**Comment by chocolatkey** [comment]
@einstein95 goddamit. one min

**Comment by chocolatkey** [comment]
@einstein95 ok that was ugly but it's fixed

**Comment by chocolatkey** [comment]
@einstein95 I think the initial version can be merged without filters and icon. I don't really have an icon at the moment, and I'm going to possibly modify the API for CC for the filters which may take a while

**Comment by CarlosEsco** [comment]
Update the foolslide build Gradle version

**Comment by chocolatkey** [comment]
@CarlosEsco just to double-check, `extVersionCode` ?

**Comment by CarlosEsco** [comment]
Yep

**Comment by chocolatkey** [comment]
@CarlosEsco done

**Pull request merged**
