### PR TITLE
Update all vietnamese source

### PR DESCRIPTION
**Pull request by namnguyendeveloper**

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Does blogtruyen not exist anymore?

**Comment by CarlosEsco** [comment]
Also can you add an icon for the source

**Comment by namnguyendeveloper** [comment]
Sorry for late answer. 
i'm too busy.
There some conflict problem with BlogTruyen source, so i deleted it and add again :D
i also add logo for all vietnamese sites with commit #318

**Comment by CarlosEsco** [comment]
Remove the logging.

**Comment by CarlosEsco** [comment]
The files commited only show the LH logo though

**Comment by CarlosEsco** [comment]
Can you fix https://github.com/inorichi/tachiyomi-extensions/issues/352

**Pull request merged**
