### PR TITLE
TMO Updates

### PR DESCRIPTION
**Pull request by happywillow0**
Another day, another update. 
I always feel like it is targeted towards us but I know it is more likely towards Ninemanga and other aggregation sites .

### CODE REVIEW

**Comment by MerradOklom** [comment]
Thank you for your continuous efforts on maintaining this source, but you shouldn't bother fixing it all the time, the users can use LectorManga instead (as long as it works).

**Comment by happywillow0** [comment]
I know I should give up on it but it is sort of fun to solve the challenge they throw. 
Kind of like a daily puzzle. Not that it is good use of time. 

Code updated but currently untested.

**Comment by happywillow0** [comment]
I noticed that they were just changing the /cascade page because scraping the page gets all the images at once. The cascade page is easy to scrape though but it is also easy for them to change currently.  

I switched it to the paginated option which they haven't modified.

**Comment by happywillow0** [comment]
Updated Cascade Code
Added Preferences selector for Cascade vs Paginated

Tested 1/18/20

**Comment by happywillow0** [comment]
I think this is good to review and pull. 
They haven't made any significant changes for a while now. 

The extension is set for the same primary method while there is a back up method built into the preferences in case things change.

**Pull request merged**
