### PR TITLE
japscan didnt actually work, whoops

### PR DESCRIPTION
**Pull request by az4521**

### CODE REVIEW

**Comment by arkon** [comment]
You forgot to bump the version.

**Comment by az4521** [comment]
well shit

**Comment by o01210o** [comment]
As a longtime user of this source, thank you so much for fixing it !
What a surprise to see its comeback 😊

**Comment by AbdullahM0hamed** [comment]
"kindly direct an equivalent (equivalent to the gratitude displayed) amount of hatred to $izurpp" ~az, probably

**Pull request merged**
