### PR TITLE
Remove TMO (1/3)

### PR DESCRIPTION
**Pull request by happywillow0**
Site actively does not want us. I will accept them working with us if they want to have app support. 
I think I might even accept them to inject their own ads that say visit us on the web. 

Part 1/3 - Remove build so it doesn't build. 
Part 2/3 - Rest of code
Part 3/3 - Repo / apk cleanup

Otherwise, comments welcome below.

### CODE REVIEW

**Comment by arkon** [comment]
Why have parts 1 and 2 separately?

**Comment by happywillow0** [comment]
I'm currently only on github web. There is no easy way of selecting multiple items to delete at once. 
I was going to hit the rest when I get home and can use the desktop version.

**Comment by happywillow0** [comment]
Also, the previous build stalled so I was thinking to get it marked as `Outdated `before the previous PR gets pushed out.

**Comment by arkon** [comment]
@edgarMejia Not sure if you have any input on this?

**Pull request closed without merging**
