### PR TITLE
Keenspot (mainly TwoKinds)

### LINKED ISSUE #457: [English] TwoKinds
http://twokinds.keenspot.com/archive/ select `a[href^="/comic"]` for chapter links
http://twokinds.keenspot.com/comic/1/ select `img[alt="Comic Page"]` for image
If no one picks it up, I'll probably get to finishing it sometime.

### PR DESCRIPTION
**Pull request by j2ghz**
the chapter list still needs a reverse and thumbnails are missing
Closes #457

### CODE REVIEW

**Comment by as280093** [comment]
hey here it the icon

**Comment by arkon** [comment]
@j2ghz Were you going to finish this?

**Comment by MGlolenstine** [comment]
@arkon I made a scraper for KeenSpot, but it's made in Kotlin and it's currently private, but I'll release it in the near future, once I get all of the quirks fixed. You can then port it over, if you'd like.

**Comment by Xeddius** [comment]
Definitely looking for this, hoping for some progress soon.

**Pull request closed without merging**
