### PR TITLE
[indonesian] neumanga source

### PR DESCRIPTION
**Pull request by ridhozhr10**
issue #463

### CODE REVIEW

**Comment by ridhozhr10** [comment]
#463

**Comment by as280093** [comment]
Hey you were missing the icons i have provided in this zip file 

[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2845542/res.zip)

**Comment by CarlosEsco** [comment]
Once icons added I will merge this

**Comment by as280093** [comment]
@CarlosEsco  Merge it without icon, I don't think @ridhozhr10 is active anymore.
I will add it afterwards.

**Pull request merged**
