### PR TITLE
[ReadComicOnline] Switch to https so searching works

### PR DESCRIPTION
**Pull request by einstein95**
Without this, the POST gets a 302 that doesn't send the search terms

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Increment the extension version code also

**Comment by cojoMan** [comment]
any update on this ? Search on RCO still not working...

**Comment by CarlosEsco** [comment]
Until it's merged it's not gonna work

**Comment by cojoMan** [comment]
I'm sorry, I don't understand what that means - until the code is merged to the main one ? How can I tell when that is ? Will I see an extension update, or ?...

**Comment by CarlosEsco** [comment]
There will be an extension update

**Comment by cojoMan** [comment]
thank you

**Comment by einstein95** [comment]
@CarlosEsco Done and rebased

**Pull request merged**
