### PR TITLE
Madara: Added Multiple Sources

### LINKED ISSUE #1279: [Source Request] [English] mangazuki.online
After seeing everyone's request for new sites since manhwahentai went down, I combed through all the alternatives and found https://www.mangazuki.online to be the best. Not only has it scrapped all the up-to-date series from manhwahentai but it seems to be updating from other sources also. I don't think they have any relations to mangazuki.co so this is a new extension. It is also more updated than www.mangazuki.me when it comes to adult manhwa. Thank you.

### PR DESCRIPTION
**Pull request by Vesnyx**
Closes #1279 

I'm not sure if these names are appropriate for the three sites since they all share the same original name. :/ 

mangazuki.club also contains both Korean and Japanese raws so I'm not sure which of the two to classify it as.

### CODE REVIEW

**Comment by Vesnyx** [comment]
Closes #1271, #1269, and #1267

**Comment by Vesnyx** [comment]
Closes #1261

**Comment by arkon** [comment]
> I'm not sure if these names are appropriate

You could just name them like URLs, like `Mangazuki.me`.

> mangazuki.club also contains both Korean and Japanese raws so I'm not sure which of the two to classify it as

Maybe you could override it to do searches based on manga/manhua/manhwa or whatever to try to distinguish between them, and have multiple versions for each language?

**Comment by Vesnyx** [comment]
Closed #1251, #1238, #1231 

I tried to use the search parameters to modify it, but since everything is paginated, I'd have to reuse everything from the search classes for every part of the code, leading to a lot duplicated code. Additionally, the search parameters used for the form data contain a huge number of variables, once again cluttering up the code.

Secondly, the only filtering that happens is for Korean raws. This means that searching for "manga" or "manwha" still returns the Korean raws. Searching for Korean raws will only return Korean comics. If someone else has a better way of implementing it that doesn't force a ton more code or they want to add the full form requests to each, feel free to do so.

**Comment by Thoasty** [comment]
First off, thank you very much for the sources. Most of them work great but I like to report a couple issues. Not sure if I should do it here or create a new issue. All mangazuki.online series give me "lateinit property name has not been initialized" error in the chapters section. 

[https://i.imgur.com/0P4ctkk.jpg](url)

A lesser issue, very few mangazuki.me series give me "no chapter found" error.

[https://i.imgur.com/wvPE80T.jpg](url)

I have a Samsung S10+ and using Madara All 1.2.4 on Tachiyomi 0.8.4

**Comment by Vesnyx** [comment]
Yeah, so I checked this out and it turns out that this cluster of sites is a massive annoyance. 

If you're on mangazuki.me, some URLs will redirect to YoManga https://mangazuki.me/manga/winner-takes-all/

Similar things occur on the other cluster of "Mangazuki" sites. Sometimes they even post the chapter as a blogpost instead, which is why you occasionally get the chapter list error. Frankly, this kinda ticks me off, and I won't be trying to fix it because of how many other domains there are (mangazuki.info, etc.). 

As for the lateinit issue, I don't actually know what's causing it. I took a look at the website's source code and the selectors look correct. It might have something to do with how they've inserted an ad alternating every chapter listing.

**Comment by Thoasty** [comment]
Thanks for looking into it. Yeah I don't mind mangazuki.me since the few series can be found elsewhere. I do hope you continue to keep mangazuki.online in mind since it's my favorite out of the bunch.

**Comment by pavan3999** [comment]
Screenshot_20190814-023619
some manga from mangazuki.online giving this error

**Pull request merged**
