### PR TITLE
Source: BoomManga

### PR DESCRIPTION
**Pull request by happywillow0**
A start to request #1578

Added:
Source Added for BoomManga
Supports Latest
Supports Most Popular
Supports Search

Missing: 
Icons

### CODE REVIEW

**Comment by happywillow0** [comment]
I knew this looked similar to another extension. I didn't know which one at first but it is using the same base as manmanga.

**Comment by happywillow0** [comment]
Found Three that look to be running on a similar platform. 
BoomManga 
ManManga
TwinsComics

Someone can make a factory for the three. 
Boommanga however does use some different CSS which my code is based on.

**Comment by happywillow0** [comment]
Made a factory instead of sleeping. 😪

**Comment by as280093** [comment]
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3716700/ic_launcher.zip)
If it's not a factory here the icon

**Pull request closed without merging**
