### PR TITLE
Mark extensions as nsfw

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**
Attempts to address #4055. Probably missing many more extensions that should be marked as nsfw, but it's a start.

### CODE REVIEW

**Comment by alessandrojean** [comment]
Can you add the flag to the SuperMangás and HiperCool extension too? They are in the Portuguese folder.

**Comment by joseph619** [comment]
Does FMReader have explicit hentai sources? Afaik, most aggregators have some NSFW content so this could potentially affect most extensions. I wonder if we should limit this to hentai majority sources only?

**Comment by arkon** [comment]
You don't need to actually bump the version numbers.

**Comment by jobobby04** [comment]
> Does FMReader have explicit hentai sources? Afaik, most aggregators have some NSFW content so this could potentially affect most extensions. I wonder if we should limit this to hentai majority sources only?

Manhwa18

**Comment by AbdullahM0hamed** [comment]
Updated

**Pull request merged**
