### PR TITLE
Fix ohmanhua decryption

### LINKED ISSUE #4292: [Bug] <OneManHua>: <Unable to match for imgPath>
## Device information
- Tachiyomi version: v0.10.4
- Android version: 10

## Source information
- Name: OneManHua
- Extension version: 1.2.4

## Steps to reproduce
Open any manga

### Expected behavior
Load manga for reading

### Actual behavior
Error shown "Unable to match imgPath"

## Other details
Nil

### PR DESCRIPTION
**Pull request by lmk1988**
Fixes #4292

### CODE REVIEW

**Comment by Gallardo26** [comment]
When will the patch be rolled out? Sorry, don't really understand how these branches thing work.

**Comment by scb261** [comment]
@Gallardo26, when maintainers of this repository will have free time to review and accept pull request from contributor, no ETA, just wait

**Comment by lmk1988** [comment]
Have added the self signed apk here in case u all wish to test before the official merge

https://github.com/lmk1988/tachiyomi-extensions/releases

Need to allow the extension in tachiyomi since it will be marked as unofficial

**Comment by Gallardo26** [comment]
@scb261 oh... thanks.

**Comment by Gallardo26** [comment]
@lmk1988 Thank You!

**Pull request merged**
