### PR TITLE
Heaven Manga extension

### PR DESCRIPTION
**Pull request by ramattos**
Heaven Manga extension ( #1220 )

### CODE REVIEW

**Comment by as280093** [comment]
hey use this res they are same as this site
https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/holymanga.net/res

**Comment by ramattos** [comment]
I didn't know your icons existed, or that the mirror site existed in the first place.

You could always replace the icons afterwards since it isn't really a functional change.

**Comment by as280093** [comment]
it isn't a functional change but if i can afterwards it cause extension version change and those who are using the extension have to update just for icons and extra pull request too

**Comment by ramattos** [comment]
Well I can add the icons if you're all okay with waiting for a few hours before I send a new pull request since I'm not at my desktop right now.

**Comment by CarlosEsco** [comment]
Yep please add when you can

**Comment by ramattos** [comment]
- Added icons from @as280093 
- Fixed behavior on chapters with no date to parse

And it's all still a single commit. @CarlosEsco you may proceed :)

**Pull request merged**
