### PR TITLE
Fix Mangapark page list empty error

### PR DESCRIPTION
**Pull request by einstein95**

### CODE REVIEW

**Comment by CarlosEsco** [comment]
build issue

**Comment by as280093** [comment]
wait 20 min i will provide new logo as old is not good

**Comment by einstein95** [comment]
@as280093 Just make a new PR as a new icon isn't part of the issue

**Comment by as280093** [comment]
@einstein95 sorry but provide a new update will cause problem if you can add in this ok but its not then i will PR afterwards

Res Folder

[res.zip](https://github.com/inorichi/tachiyomi-extensions/files/2856302/res.zip)


Logo

web_hi_res_512

**Comment by CarlosEsco** [comment]
I will wait to merge.  @einstein95. This will allow it to be just 1 build.gradle update vs 2

**Pull request merged**
