### PR TITLE
fix 45ca32d

### PR DESCRIPTION
**Pull request by Guiorgy**
fixes a mistake (I made) in 45ca32d by not using __.toRegex()__

### CODE REVIEW

**Comment by arkon** [comment]
Whoops, I missed that too.

Can you also update the version number? Could also pull out the regexes as constants.

**Comment by Guiorgy** [comment]
```kotlin
   val HTML_BR_REGEX = """<\s*br\s*\/?>""".toRegex()
   val HTML_ELEMENT_REGEX = "<[^>]*>".toRegex()

    override fun mangaDetailsParse(document: Document): SManga {
        val infoElement = document.select(mangaDetailsMainSelector)
```
__...__
```kotlin
            description = document.select(descriptionSelector)?.first()?.ownText()
                ?.replace("""^$title summary:\s""".toRegex(), "")
                ?.replace(HTML_BR_REGEX , "\n")
                ?.replace(HTML_ELEMENT_REGEX , "")
            thumbnail_url = document.select(thumbnailSelector).attr("abs:src")
        }
    }
```

Will this be fine? I actually have little experience with Kotlin (mainly use Java and C#), so don't exactly know what the equivalent of _private static final_ is

**Comment by Guiorgy** [comment]
before
&nbsp;|
V
after

**Comment by arkon** [comment]
> I actually have little experience with Kotlin (mainly use Java and C#), so don't exactly know what the equivalent of private static final is

It should be in the `companion object { }` block, but that's fine. It's not really a big deal.

**Pull request merged**
