### PR TITLE
Moved Batoto to External source added all language support

### PR DESCRIPTION
**Pull request by CarlosEsco**

### CODE REVIEW

**Comment by CarlosEsco** [comment]
build will fail until 1.3 of ext lib.  Will add the rest of the missing structure guess git didnt pick them up.

**Comment by wopian** [comment]
Would it be possible to get sources for the many other languages Batoto has now? Or at least the more used ones (Spanish/Russian)

**Comment by CarlosEsco** [comment]
I'm sure it something that could be done. Im not planning on doing currently as I'm just working on externalizing everything

**Comment by CarlosEsco** [comment]
@wopian i lied.  Should have something that supports other languages out to day.

**Comment by CarlosEsco** [comment]
Added support for every language batoto supports.  Only issue is even when setting cookies for the lang in on their website it doesn't filter out manga without chapters in that language.  So in Tachiyomi this is reflected and manga will show but be 0 chapters if the lang isn't found when parsing the chapters

**Comment by cd0rw0** [comment]
@CarlosEsco 

all lang ver. 1.3 you posted on https://github.com/inorichi/tachiyomi/pull/1101 does not recognize previously saved batoto bookmark.

whn i try to restore frm backup, it say "source not found".

**Comment by CarlosEsco** [comment]
What bookmarks do you mean?

**Comment by Sparh4wk** [comment]
@CarlosEsco 

He means, that catalogue number has changed in version 1.3 = mangas cant be restored

in previous versioun batoto have catalogue number 1.. in 1.3 its set to 1277461893384175294

in backup json file:

```
"manga": [
                "/comic/_/8♀1♂-hachi-ichi-r5525",
                "8♀1♂ [Hachi Ichi]",
                1,
                0,
                0
            ]
```

in 1.3 backup
```

"manga": [
                "/comic/_/8♀1♂-hachi-ichi-r5525",
                "8♀1♂ [Hachi Ichi]",
                1277461893384175294,
                0,
                0
            ]
```

**Comment by lordbk** [comment]
@CarlosEsco 

sorry, i meant, 
after we install ver 1.3, all batoto manga saved in my library will disappear.

**Comment by cd0rw0** [comment]
@CarlosEsco

sorry, i meant,
after we install ver 1.3, all batoto manga saved in my library will disappear.

maybe due to reason @Sparh4wk mention above

**Comment by CarlosEsco** [comment]
this should be fixed with latest from both.

**Comment by cd0rw0** [comment]
@CarlosEsco 

can we get latest apk to test. 
thanks

**Comment by CarlosEsco** [comment]
@cd0rw0 
posted dropbox apks on the other pull request

**Comment by null-dev** [comment]
I guess we can close this now :(

**Comment by CarlosEsco** [comment]
GG

**Pull request closed without merging**
