### PR TITLE
HanhanKuman thumbnails

### PR DESCRIPTION
**Pull request by SnakeDoc83**
Closes https://github.com/inorichi/tachiyomi-extensions/issues/1621

### CODE REVIEW

**Comment by ShiroSakurairo** [comment]
Sorry, I don't know if I can comment directly here, but the problem still exists. Can you try to fix it again?

**Comment by SnakeDoc83** [comment]
Try going to settings > advanced > refresh library metadata after you've installed the update.

**Comment by ShiroSakurairo** [comment]
I have updated 1.2.2 and tried "Refresh library metadata" "Uninstall and reinstall" and so on, but the problem still exists.

**Comment by SnakeDoc83** [comment]
Mayble clear cache? I don't know, on a fresh install the thumbnails work for me.

**Comment by ShiroSakurairo** [comment]
I think this may be a bug in Tachiyomi... I am sorry to bother you.

**Comment by ShiroSakurairo** [comment]
I'm sorry to bother again, I found that this problem only occurs with my own backup, I casually add a few comics and backup recovery does not appear this problem.
This is my backup file, using Dmzj/Hanhankuman/Manhuaren three sources, can you try to restore to Tachiyomi, in order to find out where the problem is?
https://file.io/31niDX

**Comment by SnakeDoc83** [comment]
Try android settings > apps > Tachiyomi > storage > clear data and then re-import your backup..

**Comment by ShiroSakurairo** [comment]
I tried to do this, but there was no change, I still can't load thumbnails... I can only think of too many backup comics causing this problem,Is it impossible to fix this?  Maybe this is really the reason for Tachiyomi's bug, not the extension...

**Pull request merged**
